CREATE TABLE IF NOT EXISTS addresses (id, customer_id, address_type, postal_code, street, number, complement, district, city, state, country, is_primary);
CREATE TABLE IF NOT EXISTS attributes (id, name, data_type);
CREATE TABLE IF NOT EXISTS brands (id, name, country, is_active, created_at, updated_at);
CREATE TABLE IF NOT EXISTS categories (id, name, slug, parent_category_id, is_active, created_at, updated_at);
CREATE TABLE IF NOT EXISTS customers (id, person_type, legal_name, trade_name, tax_id, state_registration, email, phone, is_active, created_at, updated_at);
CREATE TABLE IF NOT EXISTS employees (id, full_name, cpf, email, role, primary_location_id, hire_date, termination_date, is_active, created_at, updated_at);
CREATE TABLE IF NOT EXISTS fiscal_invoices (id, order_id, nfe_number, nfe_access_key, series, issued_at, status, total_amount, xml_storage_uri, created_at, updated_at);
CREATE TABLE IF NOT EXISTS goods_receipt_items (id, goods_receipt_id, purchase_order_item_id, quantity_received);
CREATE TABLE IF NOT EXISTS goods_receipts (id, purchase_order_id, received_by_employee_id, received_at, notes, created_at);
CREATE TABLE IF NOT EXISTS locations (id, name, location_type, postal_code, street, number, complement, district, city, state, country, is_active, created_at, updated_at);
CREATE TABLE IF NOT EXISTS order_items (id, order_id, product_variant_id, quantity, unit_price, icms_rate, ipi_rate, line_total);
CREATE TABLE IF NOT EXISTS orders (id, order_number, channel, customer_id, salesperson_id, location_id, status, subtotal, discount_amount, total, placed_at, created_at, updated_at);
CREATE TABLE IF NOT EXISTS payments (id, order_id, method, installments, amount, status, paid_at, created_at, updated_at);
CREATE TABLE IF NOT EXISTS product_suppliers (product_variant_id, supplier_id, supplier_sku, last_quoted_cost, lead_time_days, is_preferred, created_at, updated_at);
CREATE TABLE IF NOT EXISTS product_variants (id, product_id, sku, barcode_ean, sale_price, cost_price, weight_kg, icms_rate, ipi_rate, is_active, created_at, updated_at);
CREATE TABLE IF NOT EXISTS products (id, name, description, brand_id, category_id, ncm_code, unit_of_measure, is_active, created_at, updated_at);
CREATE TABLE IF NOT EXISTS purchase_order_items (id, purchase_order_id, product_variant_id, quantity_ordered, unit_cost, line_total);
CREATE TABLE IF NOT EXISTS purchase_orders (id, po_number, supplier_id, buyer_id, destination_location_id, status, currency, subtotal, total, placed_at, expected_delivery_at, created_at, updated_at);
CREATE TABLE IF NOT EXISTS return_items (id, return_id, order_item_id, quantity, action, exchange_variant_id, unit_refund_amount);
CREATE TABLE IF NOT EXISTS returns (id, return_number, order_id, customer_id, received_at_location_id, status, reason, total_refund_amount, created_at, updated_at);
CREATE TABLE IF NOT EXISTS stock_levels (product_variant_id, location_id, quantity_on_hand, reorder_point, updated_at);
CREATE TABLE IF NOT EXISTS stock_movements (id, product_variant_id, location_id, movement_type, quantity, reference_table, reference_id, employee_id, notes, occurred_at, created_at);
CREATE TABLE IF NOT EXISTS suppliers (id, legal_name, trade_name, country, tax_id, tax_id_type, email, phone, contact_name, is_active, created_at, updated_at);
CREATE TABLE IF NOT EXISTS variant_attribute_values (product_variant_id, attribute_id, value);